#!/bin/sh
# Stage this Python subprocess plugin for `sigflow-cli plugin install`.
#
# Output: ./pkg/{manifest.toml, run.sh|run.cmd, plugin.py, sigflow_sdk/}
#
# "build" = 解析本机将用的 python 解释器、检查依赖可导入、生成烙定
# 解释器的启动包装（POSIX: run.sh；Windows/Git Bash: run.cmd，壳体不经
# sh 直接 spawn）、把 Python SDK vendor 到脚本旁（脚本目录在 sys.path
# 上，无需 PYTHONPATH）。
#
#   ./build.sh                             # 用 PATH 里的 python3
#   PYTHON=~/venv/bin/python3 ./build.sh   # 指定解释器
set -eu
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Windows 装的往往只有 `python`，没有 `python3` 别名。
PYTHON="${PYTHON:-$(command -v python3 || command -v python || true)}"
[ -n "$PYTHON" ] || { echo "python3 not found on PATH (set PYTHON=...)" >&2; exit 1; }
PYTHON="$("$PYTHON" -c 'import sys; print(sys.executable)')"
"$PYTHON" -c 'import tomllib' || { echo "python >= 3.11 required (tomllib)" >&2; exit 1; }
# 插件需要第三方依赖（numpy 等）时，仿照上一行追加 import 检查

# SDK 查找：env 显式指定 → 工程内 vendored 副本（脚手架生成时拷入）
SDK_SRC="${SIGFLOW_PY_SDK:-$SCRIPT_DIR/sigflow_sdk}"
[ -d "$SDK_SRC" ] || { echo "python SDK not found at $SDK_SRC (set SIGFLOW_PY_SDK=...)" >&2; exit 1; }

PKG_DIR="$SCRIPT_DIR/pkg"
rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR/sigflow_sdk"
cp plugin.py "$PKG_DIR/"
cp "$SDK_SRC"/*.py "$PKG_DIR/sigflow_sdk/"

# 启动包装按平台生成：Windows 上壳体直接 spawn，run.sh 需要 sh 解释器
# 而系统没有，改用 cmd 能原生执行的 run.cmd。
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*) WRAPPER="run.cmd" ;;
    *)                    WRAPPER="run.sh" ;;
esac

if [ "$WRAPPER" = run.cmd ]; then
    # %~dp0 = 本文件所在目录（带尾反斜杠）；$PYTHON 此时是 Windows 路径
    # （来自 sys.executable）。
    cat > "$PKG_DIR/run.cmd" <<EOF
@echo off
rem Generated by build.sh — do not edit. Interpreter resolved at build time.
rem -B: no __pycache__ — the install dir is content-addressed.
"$PYTHON" -B "%~dp0plugin.py" %*
EOF
else
    cat > "$PKG_DIR/run.sh" <<EOF
#!/bin/sh
# Generated by build.sh — do not edit. Interpreter resolved at build time.
# -B: no __pycache__ — the install dir is content-addressed.
HERE="\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd)"
exec "$PYTHON" -B "\$HERE/plugin.py" "\$@"
EOF
    chmod +x "$PKG_DIR/run.sh"
fi

# Rewrite `command` so the staged manifest matches the generated wrapper
# (source manifest declares run.sh).
sed "s|^command = \".*\"|command = \"${WRAPPER}\"|" manifest.toml > "$PKG_DIR/manifest.toml"

cat <<EOF

Staged __PLUGIN_ID__:
  $PKG_DIR/manifest.toml   (command = "$WRAPPER")
  $PKG_DIR/$WRAPPER        (python = $PYTHON)

Install:
  sigflow-cli plugin install $PKG_DIR
EOF
